function upgrade_project()
%upgrade_project  Run the Upgrade Advisor on the top-level models in a project
%
%   Easily upgrade using the Upgrade Project tool in Simulink Project, 
%   by selecting Run Checks > Upgrade.
%   To upgrade programmatically instead, use the script below.
%
%   Use the Simulink Project Dependency Analysis to find the top-level
%   models in the current project, and then run the Upgrade Advisor on
%   them.
%
%   upgrade_project()

%   Copyright 2016 The MathWorks, Inc.

% Use the Simulink Project API to perform a file dependency analysis to get
% the list of top-level models:
project = simulinkproject;
[topModels, topModelsWithChildren] = find_top_models; %#ok<ASGLU>

% For this example, only upgrade the models that have children
% (slproject_f14). To run on all the models, replace
% topModelsWithChildren with topModels in the line below:
modelsToUpgrade = topModelsWithChildren;

reportFiles = cell(size(modelsToUpgrade));
for index = 1:numel(modelsToUpgrade)
    thisModel = modelsToUpgrade{index};
    disp(['Upgrading the model ' thisModel]);
    
    upgrader = upgradeadvisor(thisModel);    
    upgrader.upgrade;
    
    % Update the list of reports generated by the upgrade:
    reportFiles{index} = upgrader.ReportFile;
end

% Refresh the source control status to ensure that MDL files that have been
% converted to SLX files are shown in the Modified Files view.
project.refreshSourceControl;

end
